---
driver:
  name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 8080, host: 9090, auto_correct: true}]
    - ["private_network", {ip: "33.33.33.10"}]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

  - name: centos-6.5
    run_list:
      - recipe[yum]

  - name: centos-7.0
    run_list:
      - recipe[yum]

suites:
  - name: jenkins
    run_list:
      - recipe[git]
      - recipe[build-essential]
      - recipe[emacs]
      - recipe[pipeline::jenkins]
      # - recipe[chef-zero]
      - recipe[pipeline::knife]
      - recipe[pipeline::berkshelf]
      - recipe[pipeline::lint_test]
      - recipe[pipeline::cookbooks]
    attributes:
      # chef-zero:
      #   start: true
      build-essential:
        compile_time: true

